/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package figure_geometriche;

import static java.lang.Math.sqrt;
import javax.swing.JOptionPane;

/**
 *
 * @author Maurizio
 */
public class Circonferenza extends javax.swing.JFrame {

    
    float xc;
    float yc;
    float r;
    
    float alfa;
    float beta;
    float gamma;
    
    
    int Errore=0;
    
    
    public Circonferenza() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextI_xc = new javax.swing.JTextField();
        TextI_yc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextI_r = new javax.swing.JTextField();
        TextO_equazione = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Text_alfa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Text_beta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Text_gamma = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("CIRCONFERENZA");

        TextI_xc.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                TextI_xcAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TextI_xcAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                TextI_xcAncestorRemoved(evt);
            }
        });
        TextI_xc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextI_xcMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextI_xcMousePressed(evt);
            }
        });
        TextI_xc.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                TextI_xcComponentHidden(evt);
            }
        });
        TextI_xc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextI_xcActionPerformed(evt);
            }
        });

        TextI_yc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextI_ycMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextI_ycMousePressed(evt);
            }
        });
        TextI_yc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextI_ycActionPerformed(evt);
            }
        });

        jLabel3.setText("Inserisci  yc");

        jLabel4.setText("Inserisci  xc");

        jLabel6.setText("Inserisci raggio");

        TextI_r.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextI_rMousePressed(evt);
            }
        });

        TextO_equazione.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TextO_equazione.setForeground(new java.awt.Color(0, 204, 0));
        TextO_equazione.setText("—");

        jButton1.setText("FATTO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Avendo centro e raggio");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Avendo equazione");

        Text_alfa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Text_alfaMousePressed(evt);
            }
        });

        jLabel7.setText("X² + Y² + ");

        jLabel8.setText("+");

        Text_beta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Text_betaMousePressed(evt);
            }
        });

        jLabel9.setText("+");

        Text_gamma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Text_gammaMousePressed(evt);
            }
        });

        jLabel10.setText("= 0");

        jButton2.setText("FATTO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Centro");

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel11.setText("(");

        jLabel13.setText(")");

        jLabel14.setText("Raggio");

        jTextField2.setEditable(false);

        jLabel15.setText("X");

        jLabel16.setText("Y");

        jMenu1.setText("Aiuto");

        jMenuItem1.setText("Caratteristiche");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Formule");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TextI_xc, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(TextI_yc)
                            .addComponent(TextI_r))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)))
                        .addGap(54, 54, 54))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(193, 193, 193))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(230, 230, 230))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextO_equazione, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Text_alfa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Text_beta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Text_gamma, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel5)))
                .addGap(0, 74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextI_xc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextI_yc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextI_r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(TextO_equazione, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Text_alfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Text_beta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Text_gamma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextI_xcAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TextI_xcAncestorMoved

    }//GEN-LAST:event_TextI_xcAncestorMoved

    private void TextI_xcAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TextI_xcAncestorAdded

    }//GEN-LAST:event_TextI_xcAncestorAdded

    private void TextI_xcAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TextI_xcAncestorRemoved

    }//GEN-LAST:event_TextI_xcAncestorRemoved

    private void TextI_xcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextI_xcMouseClicked

    }//GEN-LAST:event_TextI_xcMouseClicked

    private void TextI_xcMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextI_xcMousePressed
         TextO_equazione.setText("—");       
    }//GEN-LAST:event_TextI_xcMousePressed

    private void TextI_xcComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TextI_xcComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_TextI_xcComponentHidden

    private void TextI_xcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextI_xcActionPerformed

    }//GEN-LAST:event_TextI_xcActionPerformed

    private void TextI_ycMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextI_ycMouseClicked

    }//GEN-LAST:event_TextI_ycMouseClicked

    private void TextI_ycMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextI_ycMousePressed
         TextO_equazione.setText("—");      
    }//GEN-LAST:event_TextI_ycMousePressed

    private void TextI_ycActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextI_ycActionPerformed

    }//GEN-LAST:event_TextI_ycActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
            
            Principale.SCELTA=2;
            ImageTest i= new ImageTest();
        try {
            i.loadimage("Formule_circonferenza");
        } catch (Exception ex) {     
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         
        Principale.SCELTA=1;
              ImageTest i= new ImageTest();
              
        try {
            i.loadimage("C_caratteristiche");
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void TextI_rMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextI_rMousePressed
        TextO_equazione.setText("—");      
    }//GEN-LAST:event_TextI_rMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try
        {
            xc = Float.parseFloat(TextI_xc.getText());
            Errore=0;
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "     Xc non valido! Devi inserire un numero.\nAttento a non usare la virgola al posto del punto\n                         NABBO!", "Error", JOptionPane.ERROR_MESSAGE);
            TextI_xc.setText("");
            Errore=1;
        }

        try
        {
            yc = Float.parseFloat(TextI_yc.getText());
            Errore=0;
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "     Yc non valido! Devi inserire un numero.\nAttento a non usare la virgola al posto del punto\n                         NABBO!", "Error", JOptionPane.ERROR_MESSAGE);
            TextI_yc.setText("");
            Errore=1;
        }

        try
        {
            r = Float.parseFloat(TextI_r.getText());
            Errore=0;
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "     raggio non valido! Devi inserire un numero.\nAttento a non usare la virgola al posto del punto\n                         NABBO!", "Error", JOptionPane.ERROR_MESSAGE);
            TextI_r.setText("");
            Errore=1;
        }

        float gamma=(xc*xc)+(yc*yc)-(r*r);
        System.out.println("gamma = "+gamma);

        if(Errore==0)
        TextO_equazione.setText("X² + Y² +"+(-2*xc)+"x +"+(-2*yc)+"y +"+gamma+" = 0");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        try
        {
            alfa = Float.parseFloat(Text_alfa.getText());
            Errore=0;
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "     Alfa non valido! Devi inserire un numero.\nAttento a non usare la virgola al posto del punto\n                         NABBO!", "Error", JOptionPane.ERROR_MESSAGE);
            Errore=1;
        }
        
        
         try
        {
            beta = Float.parseFloat(Text_beta.getText());
            Errore=0;
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "     Beta non valido! Devi inserire un numero.\nAttento a non usare la virgola al posto del punto\n                         NABBO!", "Error", JOptionPane.ERROR_MESSAGE);
            Errore=1;
        }
        
        
          try
        {
            gamma = Float.parseFloat(Text_gamma.getText());
            Errore=0;
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "     Gamma non valido! Devi inserire un numero.\nAttento a non usare la virgola al posto del punto\n                         NABBO!", "Error", JOptionPane.ERROR_MESSAGE);
            Errore=1;
        }
         
      float raggio = (float) sqrt(  (alfa*alfa)/4   + (beta*beta)/4    - gamma);
              
           if(Errore==0)
           {
              jTextField1.setText(""+(-(alfa/2))+" , "+(-(beta/2))+"");
              jTextField2.setText(""+raggio+"");
           
           }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Text_alfaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text_alfaMousePressed
              jTextField1.setText("");
              jTextField2.setText("");       
        
    }//GEN-LAST:event_Text_alfaMousePressed

    private void Text_betaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text_betaMousePressed
         jTextField1.setText("");
              jTextField2.setText(""); 
    }//GEN-LAST:event_Text_betaMousePressed

    private void Text_gammaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text_gammaMousePressed
         jTextField1.setText("");
              jTextField2.setText(""); 
    }//GEN-LAST:event_Text_gammaMousePressed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextI_r;
    private javax.swing.JTextField TextI_xc;
    private javax.swing.JTextField TextI_yc;
    private javax.swing.JLabel TextO_equazione;
    private javax.swing.JTextField Text_alfa;
    private javax.swing.JTextField Text_beta;
    private javax.swing.JTextField Text_gamma;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
