/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package figure_geometriche;

import static java.lang.Math.pow;
import static java.lang.Math.sqrt;
import javax.swing.JOptionPane;

/**
 *
 * @author Maurizio
 */
public class Sfera extends javax.swing.JFrame {

  
      float raggio;
      float volume;
      float superficie;
      float pgreco= (float) 3.14;
      
      boolean raggiovuoto=true;
      boolean volumevuoto=true;
      boolean superficievuoto=true;
     
    
    public Sfera() {
        initComponents();
         setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextI_raggio = new javax.swing.JTextField();
        TextI_volume = new javax.swing.JTextField();
        TextI_superficie = new javax.swing.JTextField();
        TextO_volume = new javax.swing.JTextField();
        TextO_raggio = new javax.swing.JTextField();
        TextO_superficie = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bFatto = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("SFERA");

        jLabel3.setText("Inserisci  volume");

        jLabel4.setText("Inserisci  raggio");

        jLabel6.setText("Inserisci superficie");

        TextI_raggio.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                TextI_raggioAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TextI_raggioAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                TextI_raggioAncestorRemoved(evt);
            }
        });
        TextI_raggio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextI_raggioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextI_raggioMousePressed(evt);
            }
        });
        TextI_raggio.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                TextI_raggioComponentHidden(evt);
            }
        });
        TextI_raggio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextI_raggioActionPerformed(evt);
            }
        });

        TextI_volume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextI_volumeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextI_volumeMousePressed(evt);
            }
        });
        TextI_volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextI_volumeActionPerformed(evt);
            }
        });

        TextI_superficie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextI_superficieMousePressed(evt);
            }
        });

        TextO_volume.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, TextI_volume, org.jdesktop.beansbinding.ELProperty.create("${text}"), TextO_volume, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        TextO_raggio.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, TextI_raggio, org.jdesktop.beansbinding.ELProperty.create("${text}"), TextO_raggio, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        TextO_raggio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextO_raggioActionPerformed(evt);
            }
        });

        TextO_superficie.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, TextI_superficie, org.jdesktop.beansbinding.ELProperty.create("${text}"), TextO_superficie, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Raggio                 :");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Superficie           :");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Volume                :");

        bFatto.setText("FATTO");
        bFatto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFattoActionPerformed(evt);
            }
        });

        jMenu1.setText("Aiuto");

        jMenuItem1.setText("Caratteristiche");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Formule");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextI_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TextO_superficie)
                        .addComponent(TextO_volume)
                        .addComponent(TextI_raggio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextI_superficie, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextO_raggio, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(bFatto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(TextI_raggio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextI_volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextI_superficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(bFatto)
                        .addGap(37, 37, 37)
                        .addComponent(TextO_raggio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TextO_volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TextO_superficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        Principale.SCELTA=1;
        ImageTest i= new ImageTest();

        try {
            i.loadimage("S_caratteristiche");
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        Principale.SCELTA=2;
        ImageTest i= new ImageTest();
        try {
            i.loadimage("Formule_sfera");
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void TextI_raggioAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TextI_raggioAncestorMoved

    }//GEN-LAST:event_TextI_raggioAncestorMoved

    private void TextI_raggioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TextI_raggioAncestorAdded

    }//GEN-LAST:event_TextI_raggioAncestorAdded

    private void TextI_raggioAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TextI_raggioAncestorRemoved

    }//GEN-LAST:event_TextI_raggioAncestorRemoved

    private void TextI_raggioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextI_raggioMouseClicked

    }//GEN-LAST:event_TextI_raggioMouseClicked

    private void TextI_raggioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextI_raggioMousePressed
         TextO_volume.setText("");
         TextO_superficie.setText("");
        
    }//GEN-LAST:event_TextI_raggioMousePressed

    private void TextI_raggioComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TextI_raggioComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_TextI_raggioComponentHidden

    private void TextI_raggioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextI_raggioActionPerformed

    }//GEN-LAST:event_TextI_raggioActionPerformed

    private void TextI_volumeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextI_volumeMouseClicked

    }//GEN-LAST:event_TextI_volumeMouseClicked

    private void TextI_volumeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextI_volumeMousePressed
        TextO_raggio.setText("");
         TextO_superficie.setText("");
       
    }//GEN-LAST:event_TextI_volumeMousePressed

    private void TextI_volumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextI_volumeActionPerformed

    }//GEN-LAST:event_TextI_volumeActionPerformed

    private void TextI_superficieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextI_superficieMousePressed
                  TextO_raggio.setText("");
         TextO_volume.setText("");
    }//GEN-LAST:event_TextI_superficieMousePressed

    private void TextO_raggioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextO_raggioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextO_raggioActionPerformed

    
    
    
    
    public void Calcola_Raggio()
    {
        float a=(3*volume)/(4*pgreco);
        float e=(float)1/3;
        
        
         raggio= (float)pow(a,e);                 //Radice cubica
    }
    
    
     public void Calcola_Raggio2()
    {
         raggio=(float)sqrt(superficie/(4*pgreco));
    }
    
    
     public void Calcola_Volume()
    {
       float a=(float)4/3;
       volume=a*pgreco*(raggio*raggio*raggio);
    }
     
  
     public void Calcola_Superficie()
    {
        superficie=4*pgreco*(raggio*raggio);
    }
     
    
    
    
    
    private void bFattoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFattoActionPerformed

        //Input : lato
        try
        {

            //prendo il float nella text del lato
            raggio = Float.parseFloat(TextI_raggio.getText());
            //se lo trovo allora latovuoto è falso
            raggiovuoto=false;

        }
        catch(NumberFormatException e)
        {
            //altrimenti è vero
            raggiovuoto=true;
        }

        //Input : perimetro
        try
        {

            //prendo la stringa che cè nella textinputperim e la inserisco nella variabile perim trasformandola in float
            volume = Float.parseFloat(TextI_volume.getText());
            volumevuoto=false;

        }
        catch(NumberFormatException e)
        {

            volumevuoto=true;
        }

        //Input : Area
        try
        {

            //prendo la stringa che cè nella textinputperim e la inserisco nella variabile perim trasformandola in float
            superficie = Float.parseFloat(TextI_superficie.getText());
            superficievuoto=false;

        }
        catch(NumberFormatException e)
        {
            superficievuoto=true;
        }

       

        if(raggiovuoto==true&&volumevuoto==true&&superficievuoto==true)
        JOptionPane.showMessageDialog(null, "     Input non valido! Devi inserire un numero.\nAttento a non usare la virgola al posto del punto\n                         NABBO!", "Error", JOptionPane.ERROR_MESSAGE);
        else if(raggiovuoto==false)
        {
            //calcolo il perimetro avendo il lato
            Calcola_Volume();
            //calcolo l'area avendo il lato
            Calcola_Superficie();
           

          
            TextO_volume.setText(String.valueOf(volume));
            TextO_superficie.setText(String.valueOf(superficie));
        }
        else if(volumevuoto==false)
        {
            //calcolo il lato
            Calcola_Raggio();
            //per poter calcolare l'area devo prima calcolare il lato
            Calcola_Superficie();
            

            TextO_raggio.setText(String.valueOf(raggio));
            TextO_superficie.setText(String.valueOf(superficie));
           
        }
        else if(superficievuoto==false)
        {
            //calcolo il lato avendo l'area
            Calcola_Raggio2();
            //per poter calcolare il perimetro devo prima calcolare il lato
            Calcola_Volume();
           

           TextO_raggio.setText(String.valueOf(raggio));
            TextO_volume.setText(String.valueOf(volume));
           
        }
       

    }//GEN-LAST:event_bFattoActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextI_raggio;
    private javax.swing.JTextField TextI_superficie;
    private javax.swing.JTextField TextI_volume;
    private javax.swing.JTextField TextO_raggio;
    private javax.swing.JTextField TextO_superficie;
    private javax.swing.JTextField TextO_volume;
    private javax.swing.JButton bFatto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
